# Port du serveur
server.port=8080

# Nom de l'application
spring.application.name=plantuml-validator-api

# Activer les endpoints Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true